name: Connect to GCP and List Instances

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        create_credentials_file: true
        workload_identity_provider:  ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # List the instances in the project
    - name: List Buckets
      run: |-
        gsutil ls

    #  # Additional gcloud commands
    # - name: Additional Commands
    #   run: |-
    #     INSTANCE_NAME="instance-1"
    #     gcloud compute instances start $INSTANCE_NAME --zone us-central1-c