name: Connect to GCP and List Instances

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        create_credentials_file: true
        workload_identity_provider:  ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # Display GCP buckets
    - name: List Buckets
      run: |-
        gcloud auth login
        gcloud auth application-default login
        gsutil ls

    # # Upload a file to a bucket
    # - name: Upload File to Bucket
    #   run: |-
    #     FILE_PATH="${GITHUB_WORKSPACE}/path/to/file.txt"
    #     gsutil cp $FILE_PATH gs://your-bucket-name